Add arithmetic function tests
cqframework/cql-tests pull request #42
Opened 2024-08-02 00:18 UTC by antvaset

This PR adds new conformance tests for arithmetic functions. I picked all the ones from https://github.com/cqframework/clinical_quality_language/blob/7e91478/Src/java/engine/src/test/resources/org/opencds/cqf/cql/engine/execution/CqlArithmeticFunctionsTest.cql which didn't exist yet here.

Using CVL (literals only) for the expected output values.

This is independent from https://github.com/cqframework/cql-tests/pull/33.

2024-08-02 02:01 UTC, brynrhodes requested changes
I don't think we have the boundary tests sorted, there is an active thread in FHIRPath about that. Can I ask that the boundary tests be taken out of this PR and put in a separate PR?

2024-08-02 05:10 UTC, antvaset commented
Done, this PR no longer includes the new tests for `HighBoundary` and `LowBoundary`. Those are now in https://github.com/cqframework/cql-tests/pull/44.

2025-04-28 19:29 UTC, raleigh-g-thompson commented
How should we handle the cases where the server doesn't handle a set of functions?  In this case we are testing for Long values and FHIR R4 doesn't support those.

Should we have some feature in the test-runner that selective applies tests by FHIR version?

2025-04-29 17:25 UTC, brynrhodes approved these changes

2025-04-30 12:17 UTC, brynrhodes commented
Fair point, Tests, Group, and Test structures all have a `version` attribute that indicates the version of the specification in which the feature under test was introduced. Should probably add 1.5 to this.

However, CQL 1.5 does support Long even if FHIR R4 does not, so the test is valid for CQL 1.5, and we allow for this in R4 by returning/passing the value as a string:

https://build.fhir.org/ig/HL7/cql-ig/conformance.html#conformance-requirement-4-3

2025-04-30 12:51 UTC, raleigh-g-thompson approved these changes

2025-04-30 12:51 UTC, merged